### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by MRDev12** [sumitkumar1503/schoolmanagement#15]

**Comment by rajnandini-tambavekar** [comment]
Is there an issue ? can you please explain this issue ? can I work on it

**Comment by anubhavkulshresthagit** [comment]
I can't understand exactly what are you saying, if there any issue please explain it...

**Comment by Uttam-Singhh** [comment]
Is there any issue to work??

**Comment by sumitkumar1503** [comment]
i dont think there is error...closing
