### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by oyerohabib** [sumitkumar1503/schoolmanagement#8]
@sumitkumar1503 

![Screenshot (12)](https://user-images.githubusercontent.com/48946023/87535197-f5fbfb00-c64b-11ea-8c36-26f3efe3c6b2.png)

i am able to start the server successfully, and also take admission but whenever i want to login after registering, i get this error.

kindly help please

**Comment by Adityarauthan2409** [comment]
> @sumitkumar1503
> 
> i am able to start the server successfully, and also take admission but whenever i want to login after registering, i get this error.
> kindly help please

Don't change the code it is working properly
