### ISSUE TITLE
ValueError at /afterlogin

### ISSUE THREAD

**Issue by oyerohabib** [sumitkumar1503/schoolmanagement#9]
@sumitkumar1503 
i get this error after i have tried login but failed and tried to go back to another page 
![Screenshot (13)](https://user-images.githubusercontent.com/48946023/87535493-71f64300-c64c-11ea-9b53-80a50567575a.png)

kindly help please

**Comment by Adityarauthan2409** [comment]
Hey there is one more error in this project.
![Screenshot (67)](https://user-images.githubusercontent.com/54494578/91652859-d11ee400-ea4f-11ea-951f-3d3f2d1ffee7.png)

**Comment by sumitkumar1503** [comment]
Have you done migrations ?

**Comment by Adityarauthan2409** [comment]
It is working properly without any changes in code and yes don't forget the command 'python manage.py migrate'

**Comment by sumitkumar1503** [comment]
Right 😊

dont login with superuser credentials
